blank_issues_enabled: true
contact_links:
- name: Discussion about the mod
  url: https://github.com/Funkin4RPlace/Funkin4RPlace/discussions
  about: Discuss the mod on the Discussions tab (click to go there).
